image: elixir:latest

stages:
  - build
  - test
  - publish

variables:
  MIX_ENV: test

cache:
  paths:
    - _build
    - deps

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

compile:
  stage: build
  script:
    - mix compile --warnings-as-errors

test:
  stage: test
  script:
    - mix coveralls.json --trace
  after_script:
    - bash <(curl -s https://codecov.io/bash)

lint:
  stage: test
  script:
    - mix credo --strict

