image: elixir:1.11.2

stages:
  - build
  - test
  - publish

include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  MIX_ENV: test
  SAST_DEFAULT_ANALYZERS: sobelow

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - _build
    - deps

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

compile:
  stage: build
  script:
    - mix compile --warnings-as-errors

test:
  stage: test
  script:
    - mix coveralls.json --trace
  after_script:
    - bash <(curl -s https://codecov.io/bash)

lint:
  stage: test
  script:
    - mix credo --strict

publish:
  stage: publish
  script:
    - echo "hex publish ..."
