language: elixir

elixir:
  - '1.10.4'
otp_release: '23.0.4'

env:
  - MIX_ENV=test
script:
  - mix do deps.get, compile --warnings-as-errors, coveralls.json, credo --strict
after_success:
  - bash <(curl -s https://codecov.io/bash)