language: elixir

elixir:
  - '1.10.4'
otp_release: '23.0.4'

jobs:
  include:
    - elixir: '1.9.4'
      otp_release: '22.3.4.11'
env:
  - MIX_ENV=test
script:
  - mix do deps.get, compile --warnings-as-errors, credo --strict
after_success:
  - bash <(curl -s https://codecov.io/bash)